name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
        # make depends on uv
      - name: Install dependencies
        run: |
          pip install uv
          make install
      - name: Run linter and pytest
        run: |
          make lint
      - name: Run test coverage
        run: |
          make test-coverage
      - name: Generate coverage and test reports
        run: |
          python -m pytest \
            --cov=gendiff \
            --cov-report=xml \
            --junitxml=report.xml \
            tests/ || echo "Tests completed"  
      - name: SonarQubeScan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          # Проверка доступности отчетов
          [ -f coverage.xml ] && echo "coverage.xml found" || echo "coverage.xml not found"
          [ -f report.xml ] && echo "report.xml found" || echo "report.xml not found"
          
          # Запуск анализатора
          sonar-scanner \
            -Dsonar.projectKey=hexlet-boilerplates_python-package \
            -Dsonar.organization=hexlet-boilerplates \
            -Dsonar.sources=gendiff \
            -Dsonar.tests=tests \
            -Dsonar.python.coverage.reportPaths=coverage.xml \
            -Dsonar.python.xunit.reportPath=report.xml \
            -Dsonar.verbose=true